-- CategoryCommissionDefault: add proper UUID primary key, change from 1:1 to 1:N per FoodCategory.

-- 1. Drop existing foreign keys and indexes
ALTER TABLE `CATEGORY_COMMISSION_DEFAULT` DROP FOREIGN KEY `CATEGORY_COMMISSION_DEFAULT_FoodCategoryID_fkey`;
ALTER TABLE `CATEGORY_COMMISSION_DEFAULT` DROP FOREIGN KEY `CATEGORY_COMMISSION_DEFAULT_UpdatedByAdminID_fkey`;

DROP INDEX `CATEGORY_COMMISSION_DEFAULT_IsActive_idx` ON `CATEGORY_COMMISSION_DEFAULT`;
DROP INDEX `CATEGORY_COMMISSION_DEFAULT_UpdatedByAdminID_idx` ON `CATEGORY_COMMISSION_DEFAULT`;

-- 2. Drop primary key (FoodCategoryID)
ALTER TABLE `CATEGORY_COMMISSION_DEFAULT` DROP PRIMARY KEY;

-- 3. Add new UUID primary key column
ALTER TABLE `CATEGORY_COMMISSION_DEFAULT`
ADD COLUMN `CommissionDefaultID` VARCHAR(36) NOT NULL FIRST;

-- 4. Populate existing rows with UUIDs
UPDATE `CATEGORY_COMMISSION_DEFAULT` SET `CommissionDefaultID` = UUID() WHERE `CommissionDefaultID` = '';

-- 5. Set new primary key
ALTER TABLE `CATEGORY_COMMISSION_DEFAULT` ADD PRIMARY KEY (`CommissionDefaultID`);

-- 6. Add unique constraint and indexes
ALTER TABLE `CATEGORY_COMMISSION_DEFAULT` ADD UNIQUE INDEX `CATEGORY_COMMISSION_DEFAULT_FoodCategoryID_EffectiveFrom_key`(`FoodCategoryID`, `EffectiveFrom`);
CREATE INDEX `CATEGORY_COMMISSION_DEFAULT_FoodCategoryID_idx` ON `CATEGORY_COMMISSION_DEFAULT`(`FoodCategoryID`);
CREATE INDEX `CATEGORY_COMMISSION_DEFAULT_IsActive_idx` ON `CATEGORY_COMMISSION_DEFAULT`(`IsActive`);
CREATE INDEX `CATEGORY_COMMISSION_DEFAULT_EffectiveFrom_EffectiveTo_idx` ON `CATEGORY_COMMISSION_DEFAULT`(`EffectiveFrom`, `EffectiveTo`);
CREATE INDEX `CATEGORY_COMMISSION_DEFAULT_UpdatedByAdminID_idx` ON `CATEGORY_COMMISSION_DEFAULT`(`UpdatedByAdminID`);

-- 7. Re-add foreign keys
ALTER TABLE `CATEGORY_COMMISSION_DEFAULT` ADD CONSTRAINT `CATEGORY_COMMISSION_DEFAULT_FoodCategoryID_fkey` FOREIGN KEY (`FoodCategoryID`) REFERENCES `FOOD_CATEGORY`(`CategoryID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `CATEGORY_COMMISSION_DEFAULT` ADD CONSTRAINT `CATEGORY_COMMISSION_DEFAULT_UpdatedByAdminID_fkey` FOREIGN KEY (`UpdatedByAdminID`) REFERENCES `ADMIN`(`AdminID`) ON DELETE SET NULL ON UPDATE CASCADE;
