-- Platform-wide fallback commission (single logical row).
CREATE TABLE `PLATFORM_COMMISSION_DEFAULT` (
    `DefaultID` VARCHAR(36) NOT NULL,
    `CommissionPercent` DECIMAL(5, 2) NOT NULL,
    `UpdatedAt` DATETIME(3) NULL,
    `UpdatedByAdminID` VARCHAR(36) NULL,

    INDEX `PLATFORM_COMMISSION_DEFAULT_UpdatedByAdminID_idx`(`UpdatedByAdminID`),
    PRIMARY KEY (`DefaultID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `PLATFORM_COMMISSION_DEFAULT` (`DefaultID`, `CommissionPercent`)
VALUES ('00000000-0000-0000-0000-000000000001', 10.00);

ALTER TABLE `PLATFORM_COMMISSION_DEFAULT`
ADD CONSTRAINT `PLATFORM_COMMISSION_DEFAULT_UpdatedByAdminID_fkey`
FOREIGN KEY (`UpdatedByAdminID`) REFERENCES `ADMIN`(`AdminID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Default commission per food category.
CREATE TABLE `CATEGORY_COMMISSION_DEFAULT` (
    `FoodCategoryID` VARCHAR(36) NOT NULL,
    `CommissionPercent` DECIMAL(5, 2) NOT NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `EffectiveFrom` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `EffectiveTo` DATETIME(3) NULL,
    `UpdatedAt` DATETIME(3) NULL,
    `UpdatedByAdminID` VARCHAR(36) NULL,

    INDEX `CATEGORY_COMMISSION_DEFAULT_IsActive_idx`(`IsActive`),
    INDEX `CATEGORY_COMMISSION_DEFAULT_UpdatedByAdminID_idx`(`UpdatedByAdminID`),
    PRIMARY KEY (`FoodCategoryID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `CATEGORY_COMMISSION_DEFAULT`
ADD CONSTRAINT `CATEGORY_COMMISSION_DEFAULT_FoodCategoryID_fkey`
FOREIGN KEY (`FoodCategoryID`) REFERENCES `FOOD_CATEGORY`(`CategoryID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `CATEGORY_COMMISSION_DEFAULT`
ADD CONSTRAINT `CATEGORY_COMMISSION_DEFAULT_UpdatedByAdminID_fkey`
FOREIGN KEY (`UpdatedByAdminID`) REFERENCES `ADMIN`(`AdminID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Enterprise override per category.
CREATE TABLE `ENTERPRISE_CATEGORY_COMMISSION` (
    `EnterpriseCategoryCommissionID` VARCHAR(36) NOT NULL,
    `EnterpriseID` VARCHAR(36) NOT NULL,
    `FoodCategoryID` VARCHAR(36) NOT NULL,
    `CommissionPercent` DECIMAL(5, 2) NOT NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `EffectiveFrom` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `EffectiveTo` DATETIME(3) NULL,
    `UpdatedAt` DATETIME(3) NULL,
    `UpdatedByAdminID` VARCHAR(36) NULL,

    INDEX `ENTERPRISE_CATEGORY_COMMISSION_EnterpriseID_idx`(`EnterpriseID`),
    INDEX `ENTERPRISE_CATEGORY_COMMISSION_FoodCategoryID_idx`(`FoodCategoryID`),
    INDEX `ENTERPRISE_CATEGORY_COMMISSION_UpdatedByAdminID_idx`(`UpdatedByAdminID`),
    UNIQUE INDEX `ENTERPRISE_CATEGORY_COMMISSION_EnterpriseID_FoodCategoryID_key`(`EnterpriseID`, `FoodCategoryID`),
    PRIMARY KEY (`EnterpriseCategoryCommissionID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `ENTERPRISE_CATEGORY_COMMISSION`
ADD CONSTRAINT `ENTERPRISE_CATEGORY_COMMISSION_EnterpriseID_fkey`
FOREIGN KEY (`EnterpriseID`) REFERENCES `ENTERPRISE`(`EnterpriseID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ENTERPRISE_CATEGORY_COMMISSION`
ADD CONSTRAINT `ENTERPRISE_CATEGORY_COMMISSION_FoodCategoryID_fkey`
FOREIGN KEY (`FoodCategoryID`) REFERENCES `FOOD_CATEGORY`(`CategoryID`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `ENTERPRISE_CATEGORY_COMMISSION`
ADD CONSTRAINT `ENTERPRISE_CATEGORY_COMMISSION_UpdatedByAdminID_fkey`
FOREIGN KEY (`UpdatedByAdminID`) REFERENCES `ADMIN`(`AdminID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Deduction templates (optional link from settlement lines).
CREATE TABLE `DEDUCTION_RULE` (
    `RuleID` VARCHAR(36) NOT NULL,
    `EnterpriseID` VARCHAR(36) NULL,
    `DeductionType` ENUM('PlatformFee', 'Penalty', 'Tax', 'Adjustment', 'CODHandling', 'Marketing', 'Other') NOT NULL,
    `Label` VARCHAR(255) NOT NULL,
    `FixedAmount` DECIMAL(18, 2) NULL,
    `PercentOfGross` DECIMAL(5, 2) NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `ValidFrom` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ValidTo` DATETIME(3) NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NULL,
    `CreatedByAdminID` VARCHAR(36) NULL,

    INDEX `DEDUCTION_RULE_EnterpriseID_idx`(`EnterpriseID`),
    INDEX `DEDUCTION_RULE_IsActive_idx`(`IsActive`),
    INDEX `DEDUCTION_RULE_DeductionType_idx`(`DeductionType`),
    INDEX `DEDUCTION_RULE_CreatedByAdminID_idx`(`CreatedByAdminID`),
    PRIMARY KEY (`RuleID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `DEDUCTION_RULE`
ADD CONSTRAINT `DEDUCTION_RULE_EnterpriseID_fkey`
FOREIGN KEY (`EnterpriseID`) REFERENCES `ENTERPRISE`(`EnterpriseID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `DEDUCTION_RULE`
ADD CONSTRAINT `DEDUCTION_RULE_CreatedByAdminID_fkey`
FOREIGN KEY (`CreatedByAdminID`) REFERENCES `ADMIN`(`AdminID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Applied deductions on a settlement.
CREATE TABLE `SETTLEMENT_DEDUCTION` (
    `DeductionID` VARCHAR(36) NOT NULL,
    `SettlementID` VARCHAR(36) NOT NULL,
    `Amount` DECIMAL(18, 2) NOT NULL,
    `DeductionType` ENUM('PlatformFee', 'Penalty', 'Tax', 'Adjustment', 'CODHandling', 'Marketing', 'Other') NOT NULL,
    `Reason` TEXT NULL,
    `ReferenceCode` VARCHAR(100) NULL,
    `DeductionRuleID` VARCHAR(36) NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedByAdminID` VARCHAR(36) NULL,

    INDEX `SETTLEMENT_DEDUCTION_SettlementID_idx`(`SettlementID`),
    INDEX `SETTLEMENT_DEDUCTION_DeductionType_idx`(`DeductionType`),
    INDEX `SETTLEMENT_DEDUCTION_DeductionRuleID_idx`(`DeductionRuleID`),
    INDEX `SETTLEMENT_DEDUCTION_CreatedByAdminID_idx`(`CreatedByAdminID`),
    PRIMARY KEY (`DeductionID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `SETTLEMENT_DEDUCTION`
ADD CONSTRAINT `SETTLEMENT_DEDUCTION_SettlementID_fkey`
FOREIGN KEY (`SettlementID`) REFERENCES `SETTLEMENT`(`SettlementID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SETTLEMENT_DEDUCTION`
ADD CONSTRAINT `SETTLEMENT_DEDUCTION_DeductionRuleID_fkey`
FOREIGN KEY (`DeductionRuleID`) REFERENCES `DEDUCTION_RULE`(`RuleID`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `SETTLEMENT_DEDUCTION`
ADD CONSTRAINT `SETTLEMENT_DEDUCTION_CreatedByAdminID_fkey`
FOREIGN KEY (`CreatedByAdminID`) REFERENCES `ADMIN`(`AdminID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Snapshot commission applied per order line (filled when order is priced/confirmed).
ALTER TABLE `ORDER_DETAIL` ADD COLUMN `AppliedCommissionPercent` DECIMAL(5, 2) NULL;
ALTER TABLE `ORDER_DETAIL` ADD COLUMN `CommissionLineAmount` DECIMAL(18, 2) NULL;
